### ISSUE TITLE
Need installers for macOS and Windows

### ISSUE THREAD

**Issue by jilavsky** [nexusformat/HDF5-External-Filter-Plugins#21]
Since some of these compressions seem to be provided to users in "take home" Nexus files, I need to support reading files with these compressions in downstream tools (in my case Igor Pro). Many, if not most, users using Igor Pro are not able to compile plugins, they have never done it and will never do so. I would be happy to provide users with link to installers, but I do not see distributable installers for these compression plugins. This creates real barrier for our users to utilize Nexus files. Can maintainers create installers for recent versions of macOS and Windows 7, 10, and 11, please?

**Comment by prjemian** [comment]
> in my case Igor Pro

**Comment by rayosborn** [comment]
My comment wasn't meant to be either/or. I presume some kind of stand-alone installer would be helpful, but for people who use Python, it would also be helpful to have a `conda` installation (assuming `pip` is tricky for non-Python code), to allow it be declared as a dependency.
