### ISSUE TITLE
Test failure on Debian Bullseye

### ISSUE THREAD

**Issue by alteholz** [nexusformat/HDF5-External-Filter-Plugins#25]
When running the tests, the following errors appear:
 "HDF5:external_filters:LZ4" start time: Nov 03 23:50 CET
Output:
----------------------------------------------------------
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 140294883367808:
  #000: ../../../src/H5D.c line 151 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: ../../../src/H5Dint.c line 337 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: ../../../src/H5L.c line 1592 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: ../../../src/H5L.c line 1833 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
(...)

The reason for this is 
   avail = H5Zfilter_avail(H5Z_FILTER_LZ4);
returns 0 and the filter does not seem to be available (please see also PR #24)

Does anybody have any idea what went wrong?
I am linking against (on Debian Bullseye):
  libbz2   1.0.8
  libhdf5  1.10.6
  liblz4    1.9.3
and use the build commands from README.md

**Comment by spanezz** [comment]
I get the same result on Debian bookworm, with:
```
libbz2-dev 1.0.8-5+b1
liblz4-1:amd64   1.9.4-1
libhdf5-dev 1.10.8+repack-1
```
